### ISSUE TITLE
queue require

### ISSUE THREAD

**Issue by slibby** [Esri/vector-tile-layer#5]
https://github.com/Esri/vector-tile-layer/blob/master/examples/dojo-config.js#L4 
`queue: "http://d3js.org/queue.v1.min"`
This file doesn't exist anymore, and the app works ok without it but should be updated to point to a real location if it's needed.

Also would be better as // instead of http:// as we work towards making this work over https://

**Comment by chelm** [comment]
@slibby the file does exist and is being used as a means to queue up tile requests. The thing is that the AMDness of the code tacks on the .js 

see http://d3js.org/queue.v1.min.js

**Comment by chelm** [comment]
Removed it from the require
