### ISSUE TITLE
Load vector tile layers in ArcGIS v4.0 beta 2

### ISSUE THREAD

**Issue by ChandlerBuck** [Esri/vector-tile-layer#7]
What is the correct method for loading a parametrized url as a vector tile layer in ArcGIS v4.0 beta 2. I am trying to load a third party vector tile layer.

**Comment by jgravois** [comment]
sorry it took me so long to see this.  in order to load a parameterized url you'll need to supply the service endpoint in the same manner defined in the [mapbox-gl-style-spec](https://www.mapbox.com/mapbox-gl-style-spec/#types-sources).

``` js
"sources": {
  "osm": {
    "type": "vector",
    "tiles": [ "https://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt?api_key=[yourkey]" ]
  }
}
```

live sample: http://jsbin.com/zutujo/edit?html,output

**Comment by jgravois** [comment]
closing, but happy to chat more if you have any other questions.
